# .github/workflows/dev.yml
name: Standalone CLI
on: [push, pull_request]
jobs:
   machineStandalone:
      runs-on: ubuntu-latest
      steps:
         - uses: actions/checkout@f095bcc56b7c2baf48f3ac70d6d6782f4f553222
         - uses: docker://docker.io/fluidattacks/cli:latest
           name: machineStandalone
           with:
             args: skims scan ./config.yaml
         - name: Archive production artifacts
           uses: actions/upload-artifact@v4
           with:
                name: dist-without-markdown
                path: |
                  dist
                  !dist/**/*.md
         - name: Archive code coverage results
           uses: actions/upload-artifact@v4
           with:
                name: code-coverage-report
                path: output/test/code-coverage.html
